- name: Open ports 22 and 5432 using firewalld
  hosts: db
  become: yes
  tasks:
    - name: Allow SSH (port 22) using firewalld
      ansible.builtin.firewalld:
        port: 22/tcp
        state: enabled
        permanent: yes
        immediate: yes

    - name: Allow PostgreSQL (port 5432) using firewalld
      ansible.builtin.firewalld:
        port: 5432/tcp
        state: enabled
        permanent: yes
        immediate: yes
