- name: Open port 22 using iptables
  hosts: db
  become: yes
  tasks:
     - name: installing iptables 
       ansible.builtin.package:
           name: iptables
           state: present 

     - name: Allow SSH (port 22) using iptables
       ansible.builtin.command: iptables -A INPUT -p tcp --dport 22 -j ACCEPT
      
     - name: Allow SSH (port 5432) using iptables
       ansible.builtin.command: iptables -A INPUT -p tcp --dport 5432 -j ACCEPT