- name: Open ports using iptables
  hosts: all
  become: yes
  tasks:
    - name: Add iptables rules for ports 22, 80, 443
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      loop:
        - 22
        - 80
        - 443


