- name: Open ports using iptables
  hosts: all
  become: yes
  tasks:
 - name: Open ports using iptables
  hosts: all
  become: yes
  tasks:
    - name: Add iptables rules
      ansible.builtin.shell: |
        X="
          *filter
          :INPUT ACCEPT [0:0]
          :FORWARD ACCEPT [0:0]
          :OUTPUT ACCEPT [0:0]
          -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
          -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
          -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
          COMMIT
        "
        echo "$X" | sudo iptables-restore --noflush
