- name: nginx installation
  hosts: all
  become: yes
  vars:
    ansible_ssh_private_key_file: /home/ansible/aws.pem
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
