- name: Manage firewall using iptables
  hosts: all
  become: yes

  tasks:
    - name: Allow SSH (port 22) using iptables
      ansible.builtin.command: iptables -A INPUT -p tcp --dport 22 -j ACCEPT

    - name: Allow HTTP (port 80) using iptables
      ansible.builtin.command: iptables -A INPUT -p tcp --dport 80 -j ACCEPT

    - name: Allow HTTPS (port 443) using iptables
      ansible.builtin.command: iptables -A INPUT -p tcp --dport 443 -j ACCEPT
