- name: Open port 22 in firewalld
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python  # or the path to a compatible Python interpreter
  tasks:
    - name: Allow SSH (port 22) in firewalld
      ansible.builtin.firewalld:
        port: 22/tcp
        permanent: yes
        state: enabled
