- name: Open port 22 using iptables
  hosts: all
  become: yes

  tasks:
    - name: Allow SSH (port 22) using iptables
      ansible.builtin.command: iptables -A INPUT -p tcp --dport 22 -j ACCEPT
      
