- name: Manage firewall using ufw
  hosts: all
  become: yes  # Ensure appropriate privileges are set

  tasks:
    - name: Enable SSH (port 22) using ufw
      ansible.builtin.command: ufw allow 22

    - name: Enable HTTP (port 80) using ufw
      ansible.builtin.command: ufw allow 80/tcp

    - name: Enable HTTPS (port 443) using ufw
      ansible.builtin.command: ufw allow 443/tcp
