- name: Open ports 22, 80, 443 in firewall
  hosts: all
  become: yes

  tasks:
    - name: Open port 22 (SSH)
      ansible.builtin.firewalld:
        service: ssh
        permanent: yes
        state: enabled

    - name: Open port 80 (HTTP)
      ansible.builtin.firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled

    - name: Open port 443 (HTTPS)
      ansible.builtin.firewalld:
        port: 443/tcp
        permanent: yes
        state: enabled

