- name: Open port 22 in firewalld
  hosts: all  # Replace with your target host or group
  become: yes  # Ensure appropriate privileges are set

  tasks:
    - name: Allow SSH (port 22) in firewalld
      ansible.builtin.firewalld:
        port: 22/tcp
        permanent: yes
        state: enabled
